server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cv_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  application:
    name: identity-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


#testing.app.secret=asdfsafsdfds
#testing.app.expirationMs=60000
