server:
  port: 0

spring:
  application:
    name: country-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cv_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true




