server:
  port: 8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: country-server
          uri: lb://COUNTRY-SERVICE
          predicates:
            - Path=/country-server/**
#          filters:
#            -

        - id: curriculum-vitae-service
          uri: lb://CURRICULUM-VITAE-SERVICE
          predicates:
            - Path=/curriculum-vitae/**
          #          filters:
          #            -

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity-service/**
          #          filters:
          #            -

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/profiler
      client:
        registration:
          keycloak:
            client-id: profiler-security
            client-secret: 6FjYGMisEkhjdd2wtQ1IDXZM0cxNC99y
            scope: openid
            authorization-grant-type: password
            # noinspection SpringBootApplicationYaml
            token-uri: http://localhost:8090/realms/profiler/protocol/openid-connect/token
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/profiler

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/