server:
  port: 0
spring:
  application:
    name: curriculum-vitae-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cv_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: mapping,bus-refresh,bus-env,health,circuitbreakerevents,retry  # Включение нужных эндпоинтов для мониторинга и управления
  endpoint:
    health:
      enabled: true  # Включает эндпоинт здоровья (Health)
      show-details: always  # Показывает полные детали здоровья всегда (даже без авторизации)
health:
  circuitbreakers:
    enabled: true  # Включает индикатор здоровья для всех Circuit Breakers

resilience4j:
  circuitbreaker:
    instances:
      countryServiceCircuitBreaker:
        failureRateThreshold: 50   # Порог отказов (50%). Если более 50% запросов завершаются с ошибкой, размыкается цепь (Circuit Breaker переходит в состояние "Open").
        automaticTransitionFromOpenToHalfOpenEnabled: true  # Автоматический переход из состояния "Open" в состояние "Half-Open" через определённое время ожидания.
        waitDurationInOpenState: 10s  # Время ожидания в состоянии "Open" перед переходом в "Half-Open" (10 секунд).
        slidingWindowType: COUNT_BASED  # Тип скользящего окна — на основе количества запросов (COUNT_BASED). Альтернатива — TIME_BASED (на основе времени).
        slidingWindowSize: 2  # Размер окна для отслеживания вызовов (2 последних вызова). Используется для расчета процента ошибок.
        minimumNumberOfCalls: 1  # Минимальное количество вызовов для активации анализа ошибок. Если выполнен только 1 вызов, процент ошибок будет рассчитан на его основе.
        eventConsumerBufferSize: 10  # Размер буфера для событий Circuit Breaker (хранит последние 10 событий для мониторинга).
        registerHealthIndicator: true  # Включает регистрацию индикатора состояния (Health Indicator), который позволяет мониторить статус Circuit Breaker.
        permittedNumberOfCallsInHalfOpenState: 3  # Количество вызовов, разрешённых в состоянии "Half-Open" для проверки доступности сервиса, прежде чем Circuit Breaker перейдёт в "Closed" или снова в "Open".
    circuit-breaker-aspect-order: 1  # Приоритет порядка применения аспектов для Circuit Breaker (чем ниже число, тем выше приоритет).
  retry:
    retry-aspect-order: 2  # Приоритет порядка применения аспектов для Retry (чем ниже число, тем выше приоритет). В этом случае Retry применяется после Circuit Breaker.
    instances:
      course-service:
        maxAttempts: 5  # Максимальное количество попыток повторного выполнения вызова при возникновении ошибки (всего 5 попыток).
        waitDuration: 5000  # Время ожидания между повторными попытками (5000 миллисекунд или 5 секунд).